import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { v4 as uuidv4 } from 'uuid';
import { Note } from '@/types';

export interface Folder {
  id: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  color?: string;
  isAutoGenerated?: boolean;
}

interface FolderState {
  folders: Folder[];
  
  // Actions
  createFolder: (name: string, isAutoGenerated?: boolean) => string;
  updateFolder: (id: string, data: Partial<Omit<Folder, 'id'>>) => void;
  deleteFolder: (id: string) => void;
  autoGenerateFolderName: (notes: Note[]) => string;
  findSimilarNotes: (note: Note, notes: Note[]) => Note[];
}

export const useFolderStore = create<FolderState>()(
  persist(
    (set, get) => ({
      folders: [],
      
      createFolder: (name, isAutoGenerated = false) => {
        const id = uuidv4();
        const newFolder: Folder = {
          id,
          name,
          createdAt: new Date(),
          updatedAt: new Date(),
          isAutoGenerated,
          // Assign a random color from a predefined palette
          color: getRandomColor()
        };
        
        set(state => ({
          folders: [newFolder, ...state.folders]
        }));
        
        return id;
      },
      
      updateFolder: (id, data) => {
        set(state => ({
          folders: state.folders.map(folder => 
            folder.id === id 
              ? { ...folder, ...data, updatedAt: new Date() } 
              : folder
          )
        }));
      },
      
      deleteFolder: (id) => {
        set(state => ({
          folders: state.folders.filter(folder => folder.id !== id)
        }));
      },
      
      // Generate a folder name based on common themes in notes
      autoGenerateFolderName: (notes) => {
        if (!notes.length) return "New Folder";
        
        // Try to extract common words from the notes' titles
        const titles = notes.map(note => note.title.toLowerCase());
        
        // Extract words from titles (removing common words)
        const stopWords = ["a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for", "with", "notes", "note"];
        const wordsMap: Record<string, number> = {};
        
        titles.forEach(title => {
          const words = title
            .split(/\s+/)
            .filter(word => word.length > 2 && !stopWords.includes(word));
            
          words.forEach(word => {
            wordsMap[word] = (wordsMap[word] || 0) + 1;
          });
        });
        
        // Find the most common words
        const sortedWords = Object.entries(wordsMap)
          .sort((a, b) => b[1] - a[1])
          .map(entry => entry[0]);
        
        if (sortedWords.length > 0) {
          // Capitalize first letter of each word
          const folderName = sortedWords
            .slice(0, 2)
            .map(word => word.charAt(0).toUpperCase() + word.slice(1))
            .join(" ");
            
          return folderName || "New Folder";
        }
        
        // If no common words found, use the first note's title
        if (notes[0]?.title) {
          return notes[0].title;
        }
        
        return "New Folder";
      },
      
      // Find similar notes based on content and title
      findSimilarNotes: (note, allNotes) => {
        if (!note || !note.content) return [];
        
        // Get keywords from note content and title
        const noteText = (note.title + " " + note.content).toLowerCase();
        const keywords = extractKeywords(noteText);
        
        // Score each note based on keyword matches
        return allNotes
          .filter(n => n.id !== note.id) // Don't include the current note
          .map(otherNote => {
            const otherText = (otherNote.title + " " + otherNote.content).toLowerCase();
            const score = calculateSimilarityScore(keywords, otherText);
            return { note: otherNote, score };
          })
          .filter(item => item.score > 0.3) // Only include notes with decent similarity
          .sort((a, b) => b.score - a.score) // Sort by highest score
          .slice(0, 5) // Take top 5
          .map(item => item.note);
      }
    }),
    {
      name: 'scribblesnap-folders',
      partialize: (state) => ({ folders: state.folders }),
    }
  )
);

// Helper functions for generating folder names
function extractKeywords(text: string): string[] {
  const stopWords = ["a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for", "with", "notes", "note"];
  return text
    .split(/\s+/)
    .filter(word => word.length > 2 && !stopWords.includes(word));
}

function calculateSimilarityScore(keywords: string[], text: string): number {
  const matches = keywords.filter(keyword => text.includes(keyword)).length;
  return matches / keywords.length;
}

function getRandomColor(): string {
  const colors = [
    "#4f46e5", // indigo
    "#2563eb", // blue
    "#7c3aed", // violet
    "#c026d3", // fuchsia
    "#db2777", // pink
    "#e11d48", // rose
    "#ea580c", // orange
    "#d97706", // amber
    "#65a30d", // lime
    "#16a34a", // green
    "#0d9488", // teal
    "#0284c7"  // light blue
  ];
  return colors[Math.floor(Math.random() * colors.length)];
} 