
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Tables, Functions } from '@/types/database';

// Extend the Database type to include our custom tables and functions
type ExtendedDatabase = Database & {
  public: {
    Tables: Tables;
    Functions: Functions;
  }
}

const SUPABASE_URL = "https://hyykxbckbypxugsujcrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eWt4YmNrYnlweHVnc3VqY3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzYyNDIsImV4cCI6MjA2MjIxMjI0Mn0.gPfir3ZSp-WfmSevNrsyK7f4Dm_6lVwBl1OPhyjJ5y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage,
  }
});
